// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVncXdCQk7XW739B66qKTaXOYkxrWeyIc',
    appId: '1:128629852073:android:d51d168100d3947c68a6b8',
    messagingSenderId: '128629852073',
    projectId: 'b22ehnam-notes',
    databaseURL: 'https://b22ehnam-notes-default-rtdb.firebaseio.com',
    storageBucket: 'b22ehnam-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRPwGuViClZ7QVv6oCSggevO-_XAAPkGo',
    appId: '1:128629852073:ios:b9bdb9ce41037bd468a6b8',
    messagingSenderId: '128629852073',
    projectId: 'b22ehnam-notes',
    databaseURL: 'https://b22ehnam-notes-default-rtdb.firebaseio.com',
    storageBucket: 'b22ehnam-notes.appspot.com',
    iosClientId: '128629852073-aoh215qbvfhufdr476sittkbe1vtmiam.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
